# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180121_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('global_password_change', '有权修改任意账户密码')], 'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
