# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180125_2228'),
        ('account', '0004_auto_20180122_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student',
            field=models.ForeignKey(blank=True, help_text='只有学员报名后方可为其创建账号', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Customer', verbose_name='关联学员账号'),
        ),
    ]
