# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id'], 'permissions': [('fuck_you', 'can fuck somebody'), ('eat', 'can eat')], 'verbose_name': '客户表', 'verbose_name_plural': '客户表'},
        ),
    ]
