# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180121_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'permissions': [('sb', 'can be a sb')], 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
    ]
