# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180122_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_num',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=32, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='qq',
            field=models.CharField(max_length=64, unique=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='qq_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='QQ名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(0, '转介绍'), (1, 'QQ群'), (2, '官网'), (3, '百度推广'), (4, '51CTO'), (5, '知乎'), (6, '市场推广')], verbose_name='来源'),
        ),
    ]
