# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 12:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180124_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='consultant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='课程顾问'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ClassList', verbose_name='所报班级'),
        ),
    ]
