# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180125_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.BooleanField(default=False, verbose_name='注册状态'),
        ),
    ]
