# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180125_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='customer',
            new_name='enrollment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='course',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='数额'),
        ),
    ]
